services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: postgres

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: redis

volumes:
  postgres_data:
