services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=example
  #     - DB_NAME=mydb
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: postgres

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: redis

volumes:
  postgres_data:
